apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-app-deploy
  labels:
    app: tweet-app
    environment: dev
  annotations:
    description: Ejemplo de despliegue con gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-app
  template:
    metadata:
      labels:
        app: tweet-app
        environment: dev
      annotations:
        description: tweet-app deployment pod
    spec:
      containers:
      - name: server
        image: luzta/linux-tweet-app:2.0
        ports:
        - containerPort: 80