name: "CI_CD_Pipeline_v0"
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print mensaje
        run: echo "Aplicación compilada correctamente"
